//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Data
    {
        [DisplayName("Beszállító Dolgozói ID")]
        public int SID { get; set; }

        [DisplayName("Beszállító")]
        public string Supplier { get; set; }

        [DisplayName("Beszállító alkalmazott")]
        public string WorkerName { get; set; }

        [DisplayName("Személyigazolványszám")]
        public string IDCNumber { get; set; }

        [DisplayName("Rendszám")]
        public string CarNPlate { get; set; }

        [DisplayName("Születési hely")]
        public string BirthPlace { get; set; }

        [DisplayName("Születési idõ")]
        public System.DateTime BirthDate { get; set; }

        [DisplayName("Anyja neve")]
        public string MothersName { get; set; }

        [DisplayName("Létrehozva")]
        public System.DateTime CreatedON { get; set; }
    }
}
