//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.User = new HashSet<User>();
        }

        [DisplayName("Bejelentkezés ID")]
        public int LoginID { get; set; }

        [DisplayName("Szerep ID")]
        public Nullable<int> RoleID { get; set; }

        [DisplayName("Beszállító ID")]
        public Nullable<int> SupplierID { get; set; }

        [DisplayName("Felhasználónév")]
        public string Username { get; set; }

        [DisplayName("Jelszó")]
        public string Password { get; set; }

        [DisplayName("Törölve")]
        public Nullable<bool> Isdeleted { get; set; }

        [DisplayName("Létrehozva")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
