//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Permission
    {
        [DisplayName("Felhasználó ID")]
        public int UserID { get; set; }

        [DisplayName("Jogosultság")]
        public string Permission1 { get; set; }
    
        public virtual User User { get; set; }
    }
}
