//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Problem
    {
        [DisplayName("Probléma ID")]
        public int ProblemID { get; set; }

        [DisplayName("Felhasználónév")]
        public string Username { get; set; }

        [DisplayName("Probléma")]
        public string Problem1 { get; set; }
    }
}
