//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Login = new HashSet<Login>();
        }
        [DisplayName("Beszállító ID")]
        public int SupplierID { get; set; }
        [DisplayName("Beszállító")]
        public string Supplier1 { get; set; }
        [DisplayName("Adószám")]
        public string Taxnumber { get; set; }
        [DisplayName("Telephely")]
        public string HQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
    }
}
