//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace you.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User
    {
        [DisplayName("Felhasználó ID")]
        public int UserID { get; set; }

        [DisplayName("Bejelentkezés ID")]
        public Nullable<int> LoginID { get; set; }

        [DisplayName("Név")]
        public string Name { get; set; }

        [DisplayName("Cím")]
        public string Address { get; set; }

        [DisplayName("Nem")]
        public string Gender { get; set; }

        [DisplayName("Email")]
        public string Email { get; set; }

        [DisplayName("Megye ID")]
        public Nullable<int> DistrictID { get; set; }
        public virtual District District { get; set; }
        public virtual Login Login { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
